### ISSUE TITLE
Trouble deodexing M apps

### ISSUE THREAD

**Issue by superr** [JesusFreke/smali#316]
Hello again. Real issue this time. Trying to deodex Marshmallow apps for the nexus 6 (shamu) using baksmali version 2.1.0. Running into errors when there are multiple dex files. I have attached one of the problem apps along with the boot.oat, as well as the output from the attempt. Please let me know if you need anything else. Thanks for your support :)

https://s.basketbuild.com/dlgate/devs?dev=SuperR&dl=SuperR/Testing/shamu_M_test.zip

```
superr@studio:~/android/Shamu_M/system/app/EditorsDocs$ java -jar ~/bin/baksmali.jar -x -c boot.oat -d ../../framework/arm -e /system/app/EditorsDocs/EditorsDocs.apk oat/arm/EditorsDocs.odex -o oat/arm/smali
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lcom/google/apps/docs/docos/client/mobile/model/api/DiscussionOrigin; at index 15
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1717)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:983)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 24
method: Lbpa;-><clinit>()V



Error occurred while disassembling class Lcom.qo.android.quickword.QWDrawUtils; - skipping class
org.jf.dexlib2.analysis.UnresolvedClassException: Could not resolve class Lcom/google/android/apps/docs/quickoffice/text/SupportedAssetFont;
	at org.jf.dexlib2.analysis.ClassPath.getClassDef(ClassPath.java:169)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:94)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:92)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:88)
	at org.jf.dexlib2.analysis.ClassProto$4.get(ClassProto.java:580)
	at org.jf.dexlib2.analysis.ClassProto$4.get(ClassProto.java:570)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getInstanceFields(ClassProto.java:378)
	at org.jf.dexlib2.analysis.ClassProto.getFieldByOffset(ClassProto.java:345)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1553)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:981)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lcom/qo/android/quickword/g; at index 12
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1717)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:983)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 262
method: Lcom/qo/android/quickword/b;-><clinit>()V



Error occurred while disassembling class Lcow; - skipping class
org.jf.dexlib2.analysis.UnresolvedClassException: Could not resolve class Ldkn;
	at org.jf.dexlib2.analysis.ClassPath.getClassDef(ClassPath.java:169)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:94)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:92)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:88)
	at org.jf.dexlib2.analysis.ClassProto$4.get(ClassProto.java:580)
	at org.jf.dexlib2.analysis.ClassProto$4.get(ClassProto.java:570)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getInstanceFields(ClassProto.java:378)
	at org.jf.dexlib2.analysis.ClassProto.getFieldByOffset(ClassProto.java:345)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1553)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:981)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lcom/google/android/gms/analytics/internal/BatchingStrategy; at index 14
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1717)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:983)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 463
method: Lied;-><clinit>()V

superr@studio:~/android/Shamu_M/system/app/EditorsDocs$
```

**Comment by JesusFreke** [comment]
Ah, I probably need to change baksmali so that it automatically adds the other dex files in the odex being deodexed to the classpath. In the meantime, I was able to deodex this particular example with, e.g:

baksmali -x -d system/framework/arm -d system/app/EditorsDocs/oat/arm -c boot.oat:EditorsDocs.odex  system/app/EditorsDocs/oat/arm/EditorsDocs.odex -e /system/app/EditorsDocs/EditorsDocs.apk

**Comment by andreya108** [comment]
may be this way?:
java -jar ~/bin/baksmali.jar -x -c boot.oat -d ../../framework/arm  /system/app/EditorsDocs/oat/arm/EditorsDocs.odex -o oat/arm/smali

**Comment by superr** [comment]
Thanks @JesusFreke . Works as you said. I really appreciate the help :)

**Comment by eugenesan** [comment]
Provided above solution worked for some files but failed on: android.test.runner.jar: 
```
java -Xmx512m -jar baksmali.jar -d system/framework/arm -d system/framework/oat/arm/ -e /system/framework/android.test.runner.jar -c boot.oat:android.test.runner -o /tmp/tmprfBPbh/classes.smali -x system/framework/oat/arm/android.test.runner.odex
```
```
Error occurred while loading boot class path files. Aborting.
org.jf.util.ExceptionWithContext: Cannot locate boot class path file android.test.runner
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:287)
	at org.jf.dexlib2.analysis.ClassPath.fromClassPath(ClassPath.java:198)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:67)
	at org.jf.baksmali.main.main(main.java:305)
```
I am probably missing something trivial.

**Comment by JesusFreke** [comment]
@eugenesan try:

java -Xmx512m -jar baksmali.jar -d system/framework/arm -d system/framework/oat/arm/ -e /system/framework/android.test.runner.jar -c boot.oat:android.test.runner.jar -o /tmp/tmprfBPbh/classes.smali -x system/framework/oat/arm/android.test.runner.odex


(add .jar suffix on android.test.runner in the -c option)

**Comment by eugenesan** [comment]
Opps, mybad.
I'll need to fix my script.
Thanks for help.

**Comment by eugenesan** [comment]
I've hacked a script for full marshmallow deodex (Credits goes to @jpuderer).
Since it might be useful others, here is the link: https://github.com/eugenesan/android-vendor-aospplus/blob/master/utils/deodex.py

P.S.
Not sure if this is correct place to ask but I've found something strange; in hammerhead@mra58k image there is no related apk/jar for "system/priv-app/Launcher2/oat/arm/Launcher2.odex"  8-)
Any ideas?

**Comment by superr** [comment]
Here is another app having issues, even using the workaround you posted. Thanks again for your support :)

App and boot.oat files:
https://s.basketbuild.com/dlgate/devs?dev=SuperR&dl=SuperR/Testing/shamu_M_test2.zip

Output from terminal:
```
superr@studio:~/android/Shamu_M/system/app/EditorsSheets$ java -jar ~/bin/baksmali.jar -x -d ../../framework/arm -d oat/arm -c boot.oat:EditorsSheets.odex oat/arm/EditorsSheets.odex -e /system/app/EditorsSheets/EditorsSheets.apk -o oat/arm/smali
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Ljava/lang/Object; at offset 12
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1557)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:981)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-object-quick
code address: 1692
method: Lorg/joda/time/format/g$a;-><clinit>()V

superr@studio:~/android/Shamu_M/system/app/EditorsSheets$
```

**Comment by JesusFreke** [comment]
@superr Unfortunately, it looks like that one is going to be rather difficult to handle properly. It would involve doing even more advanced static analysis than baksmali is currently doing to be able to detect the correct type at that point.

For reference, the problematic code is:

    #@68d
    .line 50911
    invoke-virtual {v0}, Lorg/joda/time/format/DateTimeFormatterBuilder;->d()Ljava/lang/Object;
    move-result-object v1
    instance-of v0, v1, Lorg/joda/time/format/c;
    if-eqz v0, :cond_7d7
    instance-of v0, v1, Lorg/joda/time/format/DateTimeFormatterBuilder$b;
    if-eqz v0, :cond_7d4
    move-object v0, v1
    nop
    nop
    iget-object-quick v0, v0, field@0xc


If you see where those two nops are, that was almost certainly a check-cast instruction in the original bytecode, which was removed when it was converted to an oat file. The check-cast was likely for Lorg/joda/time/format/DateTimeFormatterBuilder$b;. But without the check-cast instruction, the current static analysis in baksmali thinks that v0 is Ljava/lang/Object;, which doesn't have a field at offset 12.

**Comment by JesusFreke** [comment]
Hmm. I guess I might be able to add a special case for an instance-of followed immediately by a conditional on the result of the instance-of. That will solve the problem for this specific case - but to solve this problem in general would require a more advanced static analyzer, which.... isn't on the top of the list of things I want to do right now :)

I'll see if I can add the special case logic, and then I'll wait to see if this sort of issue appears in a more complex form somewhere else.

**Comment by superr** [comment]
Sounds great. Thank you for your attention on this :)

**Comment by JesusFreke** [comment]
This should be working after 398630dd. Feel free to re-open if you run into any other issues :)

**Comment by superr** [comment]
Thank you. We are getting closer for sure, but still not quite there. There are only 2 apks that are not working completely. Here they are along with the boot.oat and errors. Thanks again for your support :)

https://s.basketbuild.com/dlgate/devs?dev=SuperR&dl=SuperR/Testing/shamu_M_test3.zip

```
EditorsSheets.apk:

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Ljava/lang/Object; at offset 8
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1601)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1008)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-object-quick
code address: 1632
method: Lorg/apache/qopoi/hslf/record/cl;-><clinit>()V


EditorsSlides.apk:

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Ljava/lang/Object; at offset 8
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1601)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1008)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-object-quick
code address: 1468
method: Lorg/apache/poi/hslf/record/RecordTypes;-><clinit>()V
```

**Comment by JesusFreke** [comment]
Right... that was the issue that was fixed by 398630d :) Did you try with the latest source?

**Comment by superr** [comment]
I did use the latest source :(

**Comment by JesusFreke** [comment]
I just tried with the latest source, and confirmed it works on both apps :)

**Comment by superr** [comment]
What could be the difference? I am still using your workaround syntax from above. Is that still required?

**Comment by JesusFreke** [comment]
What does your "baksmali -v" say? :)

To deodex, I used:

    baksmali-dev -x -d system/framework/arm/ -c boot.oat:EditorsSlides.odex -d system/app/EditorsSlides/oat/arm/ system/app/EditorsSlides/oat/arm/EditorsSlides.odex -e /system/app/EditorsSlides/EditorsSlides.apk
    baksmali-dev -x -d system/framework/arm/ -c boot.oat:EditorsSheets.odex -d system/app/EditorsSheets/oat/arm/ system/app/EditorsSheets/oat/arm/EditorsSheets.odex -e /system/app/EditorsSheets/EditorsSheets.apk

**Comment by superr** [comment]
I will give that a try. Thanks for your time :)

**Comment by superr** [comment]
Your code works perfect for the following:
```
-e /system/app/EditorsSheets/EditorsSheets.apk
-e /system/app/EditorsSheets/EditorsSheets.apk:classes2.dex
```
But when I try:
```
-e /system/app/EditorsSheets/EditorsSheets.apk:classes3.dex
```
I get:
```
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Ljava/lang/Object; at offset 8
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1601)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1008)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-object-quick
code address: 1632
method: Lorg/apache/qopoi/hslf/record/cl;-><clinit>()V
```
Thanks again for your support :)

**Comment by JesusFreke** [comment]
Ah, gotcha. I didn't try the classes3.dex :) I just saw the "code address: 1632" and thought it was the same as the issue you posted previously, which had a similar code address: 1692 -- which I referred to multiple times while fixing the bug :)

I'll take a look at classes3.dex tonight. My suspicion is that it is a more complex form of the same problem, as I feared.

**Comment by superr** [comment]
Thank you for taking the time on this :)

**Comment by superr** [comment]
The Nexus 6 Marshmallow rom also contains apps such as Chrome.apk that already contain classes.dex, but also have an odex file. In the past it was safe to delete the odex file as the apk is already deodexed. Is this still the case? If not, what is the recommended method for dealing with this?

Thanks :)

**Comment by JesusFreke** [comment]
Yes, that should still be fine.

**Comment by superr** [comment]
Thanks for the info :)

**Comment by JesusFreke** [comment]
Ok, try it now :)  37d14bec should fix the issue.

**Comment by superr** [comment]
Flawless. Thank you very much. Your dedication is greatly appreciated :)
