### ISSUE TITLE
Can`t deodex

### ISSUE THREAD

**Issue by zStrikEz** [JesusFreke/smali#363]
Hello, I have LG G4 Android 6.0 firmware 20C. I can`t deodex  LGWeatherService. Arm and arm64 too.
Log arm64:
[*] Деодексация LGWeatherService.apk...
Exception in thread "main" org.jf.dexlib2.dexbacked.OatFile$InvalidOatFileException: Invalid oat magic value
	at org.jf.dexlib2.dexbacked.OatFile.<init>(OatFile.java:99)
	at org.jf.dexlib2.dexbacked.OatFile.fromInputStream(OatFile.java:133)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:140)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at org.jf.baksmali.main.main(main.java:266)
[*] ---> Ошибка деодексации "LGWeatherService.apk"
[log_decompile.txt](https://github.com/JesusFreke/smali/files/85115/log_decompile.txt)

**Comment by JesusFreke** [comment]
I just released v2.1.1, which likely fixes your issue. Can you download the new version and give it a try?

**Comment by zStrikEz** [comment]
I downloaded smali 2.1.1, but the error persists.
[log_decompile.txt](https://github.com/JesusFreke/smali/files/85820/log_decompile.txt)

**Comment by JesusFreke** [comment]
What is the exact command that baksmali is being invoked with?

**Comment by bursoft-git** [comment]
Hi JesusFreke

My utility Batch Apktool used for  LGWeatherService deodexing
It use the code

java -Xmx512m -jar baksmali-2.1.1.jar -x -c boot.oat -d "_framework\arm" "_app\LGWeatherService\oat\arm\LGWeatherService.odex" -o "_app\LGWeatherService\oat\arm\LGWeatherService\smali"

**Comment by JesusFreke** [comment]
Hmm. looks about right. Can you attach LGWeatherService.odex, so I can take a look?

**Comment by bursoft-git** [comment]
LGWeatherService.odex here https://cloud.mail.ru/public/JqBF/2xtEzrhdk
boot.oat here https://cloud.mail.ru/public/E9rX/nEcBmsupm

**Comment by JesusFreke** [comment]
It looks like this is some sort of non-standard/proprietary odex file. The magic value of the oatdata isn't the expected "oat\n", but rather "almd".

I thought it might be possible to extract and process the dex file manually, but the dex file itself also appears to be invalid/nonsensical - likely some for of encryption/obfuscation.

Looking at the embedded oat2dex command, I see a "--protection=true" argument, which I'm guessing enables their proprietary obfuscation.

I don't have any interest in supporting non-standard/non-compliant formats.

**Comment by bursoft-git** [comment]
Thanks for the detailed explanation and assistance!

**Comment by zStrikEz** [comment]
Thanks.
